name: Docker Image CI CD and Deploy to Azure

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: shenolazureuppgift3


jobs:

  # Job 1: Node.js Build and Test
  node-build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  # Job 2: Build and Push Docker Image
  docker-build-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: mr-smithers-excellent/docker-build-push@v6
      name: Build & Push Docker Image
      with:
        image: shenolosman/vite-app-dockerize
        tags: dev
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_NAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

  # Job 3: Deploy to Azure Web App for Containers
  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: docker-build-push  # Ensures Docker image is built and pushed before deployment

    steps:
    # - name: 'Login to Azure'
    #   uses: azure/login@v1
    #   with:
    #     creds: ${{ secrets.SOAZURECREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-container-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.SOAZURECREDENTIALS }}
        images: 'shenolosman/vite-app-dockerize:dev'
